network:
  num_layers: 3
  dropout: 0
  type: GRU
  size_layer: 512
dataset:
  name: Mocap_keypoints_60_stride30_new
  skeleton_file: Mocap_keypoints_60_stride30_new/skeleton.py
training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  seed: false
  load: null
  n_cpus: 8
  loss:
    type: l1
    mask: true
    factor: 100
  model_scheduler:
    type: lambdalr
    steps_epoch: 500
    rate: 0.95
  print_every: 3
  mu_sigma: false
  beta_mu_sigma: 0.5
feed_data:
  mask: true
  transforms:
    add_missing:
      pad:
      - 1
      - 0
      indep_keypoints: true
      files:
      - Mocap_keypoints_60_stride30_new/proba_missing_uniform.csv
      - Mocap_keypoints_60_stride30_new/proba_missing_length_uniform.csv
    viewinvariant: false
    normalize: false
    normalizecube: true
  verbose: 0
