project_path: DISK_project_human
project_path_type: str

dataset_name: human
dataset_name_type: str
dataset_name_help: "output name for the created dataset"

model_name: _DEFAULT_
model_name_type: str

network: transformer

debug: true
debug_type: bool

training_epochs: 1500
training_epochs_type: int
training_batch_size: 32
training_batch_size_type: int
# from experience, learning rate of 0.0001 is better for GRU and 0.001 for transformer
training_learning_rate: 0.001
training_learning_rate_type: float
training_seed: _DEFAULT_
training_seed_type: int

# load can be used to continue a training
# if a valid path is given, then the saved model will be loaded
# instead of starting from a random initialization of the weights
load_model: # example: outputs/2023-09-27_Fishv3_newnewmissing/09-26-47_STGCN_stride60

n_cpus: 8 # TOCHANGE: if no multiprocessing, put 0
n_cpus_type: int

loss:
  def: l1
  def_type: str
  mask: true
  mask_type: bool
  factor: 100
  factor_type: float
model_scheduler:
  def: lambdalr
  def_type: str
  steps_epoch: 500
  steps_epoch_type: int
  rate: 0.95
  rate_type: float
print_every: _DEFAULT_
print_every_type: int
# print_every modifies the frequency at which the model infers on the validation set and the frequency at which
# models can be saved (save when validation loss is better than previous one)


transforms:
  add_missing_pad: [1, 0]
  add_missing_pad_type: IntList
  viewinvariant: true
  viewinvariant_type: bool
  normalize: false
  normalize_type: bool
  normalizecube: true
  normalizecube_type: bool
  swap: 0.5
  swap_type: float

indep_keypoints: True
indep_keypoints_type: bool
merge_keypoints: False
merge_keypoints_type: bool

test:
  n_plots: 5
  n_plots_type: int
  threshold_pck: 0.1
  threshold_pck_type: float
  plot3d_azim: 60
  plot3d_azim_type: int
  plot3d_size: 2
  plot3d_size_type: float
  plot2d_only_holes: true
  plot2d_only_holes_type: bool
  original_coordinates: true
  original_coordinates_type: bool
  n_repeat: 1
  n_repeat_type: int
