project_path: DISK_project_human
project_path_type: str

dataset_name: human
dataset_name_type: str
dataset_name_help: "output name for the created dataset"

original_freq: _DEFAULT_
original_freq_type: int
original_freq_help: "original frequency of your data in Hz"
#
subsampling_freq: _DEFAULT_
subsampling_freq_type: int
subsampling_freq_help: "subsampling frequency. subsampling_freq <= original_freq, equal if no subsampling desired otherwise lower"

length: 20 # in number of timepoints at subsampling_freq
# a good rule of thumb is to put stride to length or length/2
length_type: int
stride: 10 # in number of timepoints at subsampling_freq
stride_type: int

discard_beginning: 0 # if not used, should be set t 0
discard_beginning_type: int
discard_end: 0  # if not used, should be set to 0
discard_end_type: int
fill_gap: 10  # linear interpolation under the provided length, done before resampling
fill_gap_type: int

drop_keypoints: [] # should be a list with formatting like the input_files entry
drop_keypoints_type: StringList
# if no name was given to keypoints just add the index of the keypoint as an integer

sequential: true
sequential_type: bool


dlc_likelihood_threshold: 0.8
dlc_likelihood_threshold_type: float

debug: false
debug_type: bool

indep_keypoints: True
indep_keypoints_help: "if False, look at sets of simultaneous missing keypoints; if True, look at each keypoint independently"
indep_keypoints_type: bool
merge_keypoints: False
merge_keypoints_type: bool
merge_keypoints_help: "if False then no merging because each combination of keypoints may not have enough data points to estimate a good missing probability distribution"