################################################################################
### config file companion of test_fillmissing.py script
### to test a trained neural network model for the imputation task
### testing will be done on artificial gaps, hence the prediction can be compared
### with ground truth
### -> the principal parameters to change are marked with TOCHANGE
################################################################################


hydra:
  run:
    # TOCHANGE: output directory
    dir: outputs/13-03-25_Rat7M_optipose/DISK_subsampled_test
    #outputs/tests/${now:%H-%M-%S}_test_model_timon
#    dir: ${evaluate.checkpoints[0]}/test_on_full_dataset
  job:
    chdir: True


dataset:
  name: Rat7M_optipose
  # TOCHANGE: stride controls the translation between two samples, need to be an integer
  # a smaller stride will produce more segments and with a higher overlap
  stride: 30
  skeleton_file: #DF3D_keypoints_60_stride5/skeleton.py # Mocap_keypoints_60_stride30_new/skeleton.py #TM_pulledxp_freq300_300stride25_new/skeleton.py

feed_data:
  mask: true
  transforms:
    viewinvariant: true
    normalize: false
    normalizecube: true
    swap: 0
  verbose: 0

evaluate:
  # TOCHANGE n_cpus, to quicken the data loading is several cpus available, if not, then put 0
  n_cpus: 6
  # batch_size can be changed: a higher batch size will speed up the script while using more memory
  # in the case of a memory error, lower the batch_size
  batch_size: 8
  checkpoints:
    # TOCHANGE: folder which contains the saved model(s)
    # if the given folder contains more than one model folder, then they will all be loaded
    # you can also list several folders
    - outputs/13-03-25_Rat7M_optipose/DISK_subsampled
  n_plots: 10
  threshold_pck: 0.01 # should be between 0 and 1, Probability of Correct Keypoint
  azim: 60
  size: 2.5
  only_holes: true
  original_coordinates: true
  suffix: ''
  name_items:
  - - network
    - type
  - - training
    - mu_sigma
  merge: true
  merge_sets_file: ''
  n_repeat: 5
