project_path:
project_path_type: str

# type_file should be one of the following: mat_dannce, mat_qualisys,simple_csv, dlc_csv, npy, df3d_pkl, sleap_h5
file_format:
file_format_type: str

data_files:
data_files_type: StringList