#!/bin/bash
set -e

cd /projects/ag-bozek/france/results_behavior
source activate env_DISK || conda activate env_DISK
yes n | python /home/frose1/DISK/DISK/create_dataset.py dataset_name=test2_multianimal_dlc_h5 original_freq=30 subsampling_freq=30 length=30 stride=30 discard_beginning=0 discard_end=-1 fill_gap=10 drop_keypoints=[] sequential=false file_type=dlc_h5 dlc_likelihood_threshold=0.01 input_files=[/projects/ag-bozek/france/behavior_data/calms21-disk-dlc/calms21-01.01-snapshot195-dlc-h5/mouse001_task1_annotator1DLC_DlcrnetStride16Ms5_calms21Jan1shuffle1_snapshot_best-195_el_filtered.h5,/projects/ag-bozek/france/behavior_data/calms21-disk-dlc/calms21-01.01-snapshot195-dlc-h5/mouse002_task1_annotator1DLC_DlcrnetStride16Ms5_calms21Jan1shuffle1_snapshot_best-195_el_filtered.h5,/projects/ag-bozek/france/behavior_data/calms21-disk-dlc/calms21-01.01-snapshot195-dlc-h5/mouse004_task1_annotator1DLC_DlcrnetStride16Ms5_calms21Jan1shuffle1_snapshot_best-195_el_filtered.h5]
python /home/frose1/DISK/DISK/create_proba_missing_files.py dataset_name=test2_multianimal_dlc_h5 indep_keypoints=True merge_keypoints=False
python /home/frose1/DISK/DISK/main_fillmissing.py network=gru hydra.run.dir=outputs/gru_test2_multianimal_dlc_h5 dataset.name=test2_multianimal_dlc_h5 dataset.skeleton_file=null training.epochs=4 training.n_cpus=6 training.print_every=2 feed_data.transforms.add_missing.indep_keypoints=true feed_data.transforms.add_missing.files=[test2_multianimal_dlc_h5/proba_missing.csv,test2_multianimal_dlc_h5/proba_missing_length.csv]
python /home/frose1/DISK/DISK/test_fillmissing.py hydra.run.dir=outputs/gru_test2_multianimal_dlc_h5/test dataset.name=test2_multianimal_dlc_h5 dataset.stride=10 dataset.skeleton_file=null feed_data.transforms.add_missing.files=[test2_multianimal_dlc_h5/proba_missing.csv,test2_multianimal_dlc_h5/proba_missing_length.csv] evaluate.checkpoints=[outputs/gru_test2_multianimal_dlc_h5] evaluate.n_repeat=1 evaluate.n_plots=2
python /home/frose1/DISK/DISK/impute_dataset.py hydra.run.dir=outputs/gru_test2_multianimal_dlc_h5/impute dataset.name=test2_multianimal_dlc_h5 dataset.skeleton_file=null evaluate.checkpoint=outputs/gru_test2_multianimal_dlc_h5 evaluate.n_plots=2 evaluate.path_to_original_files=../behavior_data/calms21-disk-dlc/calms21-01.01-snapshot195-dlc-h5